rem DAOTool Ver 5.1125
rem MS.TBMSM00 的 新增 Table 的 sql
rem 103/06/09
rem (INPUT FILE VERSION:2.0)

rem DROP TABLE MS.TBMSM00 ;
rem RENAME TABLE MS.TBMSM00 TO $TABLE_NAME_OLD;

CREATE TABLE MS.TBMSM00 (msM00Uid_MSM00 INT  NOT NULL GENERATED ALWAYS AS IDENTITY,compId_MSM00 VARCHAR (4) WITH DEFAULT '',vendorNo_MSM00 VARCHAR (10) WITH DEFAULT '',countryId_MSM00 VARCHAR (10) WITH DEFAULT '',cVendorName_MSM00 VARCHAR (100) WITH DEFAULT '',eVendorName_MSM00 VARCHAR (100) WITH DEFAULT '',abbrevName_MSM00 VARCHAR (50) WITH DEFAULT '',capital_MSM00 DECIMAL (13,0)  WITH DEFAULT 0 ,capitalCrcy_MSM00 VARCHAR (5) WITH DEFAULT '',owner_MSM00 VARCHAR (50) WITH DEFAULT '',oldVendorNo_MSM00 VARCHAR (10) WITH DEFAULT '',newVendorNo_MSM00 VARCHAR (10) WITH DEFAULT '',invoiceType_MSM00 VARCHAR (2) WITH DEFAULT '',respDept_MSM00 VARCHAR (6) WITH DEFAULT '',rejUpdDate_MSM00 CHAR (8) WITH DEFAULT '',rejCode_MSM00 VARCHAR (2) WITH DEFAULT '',rejStartDate_MSM00 CHAR (8) WITH DEFAULT '',rejEndDate_MSM00 CHAR (8) WITH DEFAULT '',rejReason_MSM00 VARCHAR (500) WITH DEFAULT '',rejPoNo_MSM00 VARCHAR (20) WITH DEFAULT '',reqDate_MSM00 CHAR (8) WITH DEFAULT '',reqTimes_MSM00 INT  WITH DEFAULT 0 ,poDate_MSM00 CHAR (8) WITH DEFAULT '',poTimes_MSM00 INT  WITH DEFAULT 0 ,attachment_MSM00 VARCHAR (20) WITH DEFAULT '',status_MSM00 VARCHAR (2) WITH DEFAULT '',isIssue_MSM00 VARCHAR (1) WITH DEFAULT '',isQuote_MSM00 VARCHAR (1) WITH DEFAULT '',isPO_MSM00 VARCHAR (1) WITH DEFAULT '',dataType_MSM00 VARCHAR (2) WITH DEFAULT '',mailId_MSM00 VARCHAR (10) WITH DEFAULT '',createMailDate_MSM00 CHAR (8) WITH DEFAULT '',confirmMailDate_MSM00 CHAR (8) WITH DEFAULT '',createDate_MSM00 CHAR (8) WITH DEFAULT '',createTime_MSM00 CHAR (6) WITH DEFAULT '',createEmplComp_MSM00 VARCHAR (4) WITH DEFAULT '',createEmpl_MSM00 VARCHAR (10) WITH DEFAULT '',updateDate_MSM00 CHAR (8) WITH DEFAULT '',updateTime_MSM00 CHAR (6) WITH DEFAULT '',updateEmplComp_MSM00 VARCHAR (4) WITH DEFAULT '',updateEmpl_MSM00 VARCHAR (10) WITH DEFAULT '', PRIMARY KEY(msM00Uid_MSM00) ) DATA CAPTURE NONE  ;

CREATE UNIQUE INDEX MS.TIMSM00 ON MS.TBMSM00 (COMPID_MSM00   ASC,vendorNo_MSM00	ASC) CLOSE NO;

GRANT  CONTROL ON TABLE MS.TBMSM00 TO USER JAVAUSER ;
GRANT  SELECT,INSERT,UPDATE,DELETE,ALTER,INDEX,REFERENCES ON TABLE MS.TBMSM00 TO USER JAVAUSER WITH GRANT OPTION ;
