rem DAOTool Ver 5.1125
rem MS.TBMSM02 的 新增 Table 的 sql
rem 103/06/09
rem (INPUT FILE VERSION:2.0)

rem DROP TABLE MS.TBMSM02 ;
rem RENAME TABLE MS.TBMSM02 TO $TABLE_NAME_OLD;

CREATE TABLE MS.TBMSM02 (msM02Uid_MSM02 INT  NOT NULL GENERATED ALWAYS AS IDENTITY,msM00Uid_MSM02 INT  NOT NULL WITH DEFAULT 0 ,compId_MSM02 VARCHAR (4) WITH DEFAULT '',vendorNo_MSM02 VARCHAR (10) WITH DEFAULT '',startDate_MSM02 CHAR (8) WITH DEFAULT '',endDate_MSM02 CHAR (8) WITH DEFAULT '',rejCode_MSM02 VARCHAR (2) WITH DEFAULT '',rejReason_MSM02 VARCHAR (500) WITH DEFAULT '',rejPoNo_MSM02 VARCHAR (20) WITH DEFAULT '',rejDept_MSM02 VARCHAR (6) WITH DEFAULT '',attachment_MSM02 VARCHAR (20) WITH DEFAULT '',appId_MSM02 VARCHAR (20) WITH DEFAULT '',createDate_MSM02 CHAR (8) WITH DEFAULT '',createTime_MSM02 CHAR (6) WITH DEFAULT '',createEmplComp_MSM02 VARCHAR (4) WITH DEFAULT '',createEmpl_MSM02 VARCHAR (10) WITH DEFAULT '',updateDate_MSM02 CHAR (8) WITH DEFAULT '',updateTime_MSM02 CHAR (6) WITH DEFAULT '',updateEmplComp_MSM02 VARCHAR (4) WITH DEFAULT '',updateEmpl_MSM02 VARCHAR (10) WITH DEFAULT '', PRIMARY KEY(msM02Uid_MSM02,msM00Uid_MSM02) ) DATA CAPTURE NONE  ;

GRANT  CONTROL ON TABLE MS.TBMSM02 TO USER JAVAUSER ;
GRANT  SELECT,INSERT,UPDATE,DELETE,ALTER,INDEX,REFERENCES ON TABLE MS.TBMSM02 TO USER JAVAUSER WITH GRANT OPTION ;
